### ISSUE TITLE
Floodlight throwing java.lang.ClassNotFoundException: org.restlet.engine.ssl.SslUtils while trying to set up REST API using HTTPS

### ISSUE THREAD

**Issue by atharvak21** [floodlight/floodlight#779] opened 2018-03-21 03:50 UTC
Hi! I am trying to set up my restserver to use HTTPS on port 8081.

However, when I try to start the controller, it throws out this exception:

<img width="1297" alt="screen shot 2018-03-20 at 9 48 50 pm" src="https://user-images.githubusercontent.com/23248972/37693938-8d6be6ae-2c88-11e8-9a9f-b1b67cd00785.png">

Any help in resolving this issue will be much appreciated!
Thanks!

**Comment by QingWang0909** [comment] 2018-03-21 04:06
@atharvak21 this looks like is not a bug but a problem. We typically reserve "Issue" as a place to report a potentially Floodlight bug that needs to be resolved. 

Do you mind to re-post this question to our Floodlight mailing list (floodlight-dev@openflowhub.org) one more time? We'll be happy to help you resolve the issue there. Thanks for your kind understanding! 

I'll close this issue for now -- feel free to re-open it if you think this is a Floodlight bug. Thanks.

**Closed** 2018-03-21 04:06 UTC
