### ISSUE TITLE
Static Flow Pusher cookie issue

### ISSUE THREAD

**Issue by rshahab** [floodlight/floodlight#527] opened 2015-04-21 13:39 UTC
I noticed that when a cookie value is defined on the static flow pusher API it is ignored. In the output below cookie=0 is requested but the flow mod request pushed to the switch uses cookie=45035997351236006. This value is confirmed via wireshark. Is there a reason that the API is ignoring the cookie requested value?

root@ubuntu:/home/rshahab# curl -d '{"switch": "00:01:ae:08:ff:00:00:00", "name":"flow-mod-1", "cookie":"0", "priority":"11", "in_port":"1","active":"true", "actions":"output=2"}' http://192.168.87.128:8080/wm/staticflowpusher/json

root@ubuntu:/home/rshahab# root@http://192.168.87.128:8080/wm/staticflowpusher/list/all/json
{"00:01:ae:08:ff:00:00:00":[{"flow-mod-1":{"version":"OF_13","command":"ADD","cookie":"45035997351236006","priority":"11","idleTimeoutSec":"0","hardTimeoutSec":"0","outPort":"any","flags":"1","cookieMask":"0","outGroup":"any","match":{"in_port":"1"},"instructions":{"instruction_apply_actions":{"output":"2"}}}}]}root@ubuntu:/home/rshahab#

**Comment by rizard** [comment] 2015-05-01 17:52
@rshahab The SFP uses it's own cookie to identify flows when they're removed. Is there a reason you want to use cookies? They're typically for ease of modifying/removing flows later.

**Comment by rshahab** [comment] 2015-05-03 11:27
Much thanks for the response. I'm testing on a hybrid OF switch that uses the most significant bits to identify service context to apply the flow. This means having to use preset values in the cookie. I've found where it's defined in the java files so I can set this statically and then recompile.

Bigger issue I've found is the 16 bit limit for the incoming port. Switch uses 32 bit for the port ID so can get an incoming port defined either.

Regards,
Reza

**Comment by rizard** [comment] 2015-05-03 11:47
Floodlight stores them all as 32-bit ints within an OFPort type. This was a concern with Floodlight v0.91 and earlier but is addressed in v1.0 and up.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by rshahab** [comment] 2015-05-03 12:00
Just to confirm, does 32 bit support include setting in_port via the REST call for SFP? When I tried an integer value greater than 16 bits doesn's seem to work.

**Comment by rizard** [comment] 2015-05-03 12:12
That part of the REST API is still under construction. If you'd like to take a look and suggest/make improvements, your contribution would be welcome!

The issue is that for OpenFlow 1.0, we still need to allow the special ports 65534 for LOCAL, etc. Those same port numbers are not special anymore in 1.1 and above where ports are 32-bit. So, depending on the OF version, a port number might mean a special or ordinary port number. For now, I've imposed a limit of 16-bit ports in the SFP so that it works for all OF versions.

Sent from my iPhone

--
Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu

**Comment by rshahab** [comment] 2015-05-04 00:17
Sure. Although my skills are somewhat limited, been a couple of decades since I did any coding and that was C++, I'm pretty much a network guy.

To confirm, the relevant section is "case STR_IN_PORT" in the MatchUtils.java?

**Comment by rizard** [comment] 2015-05-04 10:49
That's correct. The issue is also likely present in ActionUtils.java for
output port.

Ryan Izard
Graduate Research/Teaching Assistant
306B Fluor Daniel Building
ECE Department, Clemson University
Clemson, SC 29634
rizard@g.clemson.edu
---------------------------------------------------
Big Switch Networks
ryan.izard@bigswitch.com

**Comment by rizard** [comment] 2016-04-29 13:24
@rshahab in_port match and output action issue you brought up is addressed in https://github.com/floodlight/floodlight/pull/657

**Closed by rizard** 2016-04-29 13:24 UTC
