### ISSUE TITLE
devicemanger problem

### ISSUE THREAD

**Issue by wenxueliu** [floodlight/floodlight#643] opened 2016-03-18 10:10 UTC
1. the device update should be pub-sub pattern.
2. Is IEntityClass , IEntityClassifierService and IEntityClassListener is  redundance,  a map between  deviceKey and entity  is perfer ?

**Comment by rizard** [comment] 2016-03-28 19:19
@wenxueliu Can you elaborate please on what the problem is? I don't quite understand. Thanks!

**Comment by rizard** [comment] 2016-04-26 18:52
@wenxueliu I'm going to close this issue to keep our list of active issues clean. Please re-open or discuss what you think the problem is on floodlight-dev@openflowhub.org.

**Closed by rizard** 2016-04-26 18:52 UTC
