### ISSUE TITLE
No FlowMod or FlowRemoved sent after receiving PortStatus down

### ISSUE THREAD

**Issue by nshelly** [floodlight/floodlight#645] opened 2016-04-04 13:23 UTC
When Floodlight receives a PORT_STATUS down message from a switch, it doesn't send out a FLOW_REMOVED  (or FLOW_MOD) message to the switch, so the old incorrect flows remain in the forwarding table.  We tested this on POX/Pyretic in reactive mode and it correctly responds to the link failure.

After receiving a "down" message, the old flows should be removed, and it should re-trigger the PACKET_IN sequence so that a new, correct rule could be installed. Currently, only after the old flows timeout in the switch (~ 5 sec), is the PACKET_IN sequence commenced and the new path discovered.

For example,

1. Setup a basic ring topology with 3 switches:
    Two hosts H1 and H2, connected to ring S1, S2 and S3

        H1 - S1 ---- S2 ---- S3 - H2
              |               |
              \-------X------/
2. Host H1 pings H2 and sets up the path S1 to S3 by default, since it's the one with the fewest hops
3. Take down link S1 -> S3.  OVS sends a PORT_STATUS down message to Floodlight.
4. Packets are dropped between H1 and H2 due to installed rules are not deleted.

This is the outbound rule from S1 that should be deleted when the link goes down, output port 3 corresponds to the interface S1 to S3.
```
sudo ovs-ofctl dump-flows s1
NXST_FLOW reply (xid=0x4):
 cookie=0x20000000000000, duration=7.822s, table=0, n_packets=7, n_bytes=686, idle_timeout=5, idle_age=1, priority=1,ip,in_port=1,dl_src=00:00:00:00:01:01,dl_dst=00:00:00:00:05:01,nw_src=10.0.0.1,nw_dst=10.0.0.2 actions=output:3
```

We have the Mininet code in our repository, if that would help.

https://github.com/floodlight/floodlight/blob/master/src/main/java/net/floodlightcontroller/core/internal/OFSwitch.java#L390

```
				for (PortChangeEvent e: events) {
					switch(e.type) {
					case DELETE:
						newPortByNumber.remove(e.port.getPortNo());
						break;
					case ADD:
						if (reason != OFPortReason.ADD) {
							// weird case
						}
						// fall through
					case DOWN:
					case OTHER_UPDATE:
					case UP:
						// update or add the port in the map
						newPortByNumber.put(e.port.getPortNo(), e.port);
						break;
```

**Comment by rizard** [comment] 2016-04-04 18:29
@nshelly Would you like to issue a pull request for this? It's not a bug, just an unimplemented feature. We'd be happy to have your contribution

**Comment by nshelly** [comment] 2016-04-13 16:04
@rizard Ok thank you for the quick feedback. Right now we are just checking out how different controllers handle link failures and will come back to this later.

**Comment by rizard** [comment] 2016-04-28 22:02
@nshelly addressed in https://github.com/floodlight/floodlight/pull/656 for the Forwarding module at least.

**Closed by rizard** 2016-04-28 22:02 UTC
